### PR TITLE
Fix Empty Chests on Third Open

### LINKED ISSUE #68: Item from chest lost on third interaction [Medium Priority]
**Bug Summary**
When a player attempts to access the item from a chest for a third time (after not picking it up the first two times), the item is missing.

**Test Case(s)**
N/A

---

**Expected behavior**
Regardless of how many times a player opens a chest, an item drop from a chest should be available if the player has not yet picked it up.

**Observed Behaviour**
If a player does not pick up an item from a chest after declining it once, that item is then lost forever.

**Steps To Reproduce**

1. For ease of testing, set all chests to have a 100% chance of dropping an item
2. Open a chest
3. Do not pick up the item
4. Open the chest a second time
5. Do not pick up the item
6. Open the chest a third time
7. The item is no longer available

**Environment**
- Version: cc9f4f6
- OS: Arch Linux
- Browser: Firefox

---

**Code Examples**
N/A

**Stack Trace**
N/A

**Screenshots**

ChestBug

**Error Report**

N/A

---

**Additional context**
Discovered while working on a branch for #64

### PR DESCRIPTION
**Pull request by Pyxxil**
GitHub Issue (If applicable): #68 

## PR Type

What kind of change does this PR introduce?
- Bugfix

## What is the current behavior?
If the player closed a chest a second time, and then went to open it any previous items would have disappeared.

## What is the new behavior?
Hopefully the player can now open the chest any number of times (while it still has items in it), and still see the item.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current upstream repo
- [ ] Added new tests to the test suite for the feature
- [ ] Tested the full test suite, and ensured that the feature does not break current build.
- [ ] Docs have been added/updated which fit (for bug fixes / features)
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal)
- [ ] Checked licensing of Frameworks/Libraries (if applicable) 

## Other information

Internal Issue (If applicable): closes #68

### CODE REVIEW

File: src/features/world/reducer.js [hunk 1]
```diff
@@ -64,7 +64,7 @@ const worldReducer = (state = initialState, { type, payload }) => {
 
         case 'OPEN_CHEST':
             const { x, y } = payload;
-            const chest = state.chests[chestName(x, y)];
+            const chest = state.chests[chestName(state.currentMap, x, y)];
```
Comment (Matteas-Eden) [inline src/features/world/reducer.js:67]: Could you offer an explanation to why such a small change fixes the bug?

Comment (Pyxxil) [reply src/features/world/reducer.js:67]: The way Chests work is that they're a different level of tile (specifically, 4 for an open chest and -2 for an empty chest). When the player knocks into a tile with value 4, the next thing that happens is a call on line 62 in file src/features/player/actions/move-player.js, which calls through to exploreChest. This will dispatch the 'OPEN_CHEST' type (which is handled in the reducer file I changed, as you can tell).

Now, as you can imagine, this is called every time the player collides with the chest. Of course, on the first time around this is fine: We didn't have any item there anyways, so it'll be generated further down the line. So the question becomes -- why is it only on the third (and subsequent entries) that this becomes an issue, and not before hand? Well, that's more to do with the 'SET_CHEST_DATA' type. So, on the second time around, once 'OPEN_CHEST' is dispatched, it will set the item to null (after the second 'SET_CHEST_DATA' dispatch) and because from then on we simply read from the chest's current data in the state every time we go to dispatch the 'SET_CHEST_DATA' we'll only ever see null, because state.chests[chestName(x, y)] will always return undefined.

As to why it always returns undefined: At one point (specifically, when I fixed the last bug about duplicated chests), I changed the chestName function so that it returned a value in the form 'mapname(x, y)', however apparently the above line got lost in the changeover. In response to that, the above function call would always return undefined simply because we were calling chestName with the wrong arguments, and thus it always returned a key that wasn't found in the object, and so always gave us undefined. Which made the following if always execute.

So, by changing the call to be correct, it doesn't always return undefined (in fact, it should only do so if the specific chest isn't already 'opened') and won't always execute the inner block, thus meaning we should be able to always reopen the chest with the correct data (because we no longer overwrite it).

**Review by Matteas-Eden — APPROVED** [review]
Thanks for the detailed explanation, LGTM
