### PR TITLE
Provide Enhancements to the Journal

### LINKED ISSUE #225: Journal slowing down game
**Bug Summary**

When you've been playing for a long time, the journal becomes so giant it actually slows down the game

**Test Case(s)**

Play through to  a high level

---

**Expected behavior**

You to be able to keep playing as normal

**Observed Behaviour**
The journal gets so heavy it slows down the game

**Steps To Reproduce**

1. Checkout the maps branch (or master if it's been merged)
2. Try playing till level 25
3. You will notice the game starts to get slower as the journal becomes overloaded

**Environment**
- Version: Maps branch
- OS: Windows 10
- Browser: Microsoft Edge

### PR DESCRIPTION
**Pull request by Pyxxil**
GitHub Issue (If applicable): #225 

## PR Type

What kind of change does this PR introduce?
- Bugfix
- Feature

## What is the current behavior?
Currently if your browser window is large enough the journal will automatically appear and stay open unless you shrink the window. The Journal also slows down the game when it gets very large, and also takes up a rather immense amount of memory.

## What is the new behavior?
The number of entries in the journal has been capped at 100, and the journal is now toggleable in large view, as well as appearing to the left of the screen while the game window is centered.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current upstream repo
- [ ] Added new tests to the test suite for the feature
- [ ] Tested the full test suite, and ensured that the feature does not break current build.
- [ ] Docs have been added/updated which fit (for bug fixes / features)
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal)
- [ ] Checked licensing of Frameworks/Libraries (if applicable) 

## Other information
I'm not spending any more time on CSS for this. I've done enough for my lifetime.

Internal Issue (If applicable): closes #225

### CODE REVIEW

**Review by Matteas-Eden — CHANGES_REQUESTED** [review]
The journal is cut-off in side view, and overlaps with the main game window.

File: src/App.js [hunk 1]
```diff
@@ -39,10 +40,50 @@ const App = ({ appState, world, dialog }) => {
...
+                </div>
+                {showFooter && <Footer />}
+            </>
+        );
+    }
+
     return (
         <>
-            <div className={`centered flex-row`}>
+            <div style={{ float: 'left' }}>
```
Comment (Matteas-Eden) [inline src/App.js:76]: This hugs the left side of the screen a little, but if you add `marginLeft: '3rem'` it makes it look a *little* nicer (though certainly not perfect).

**Review by Matteas-Eden — APPROVED** [review]
Looks good to me. I have one small styling suggestion you can feel free to ignore if you don't want to implement it.

File: src/App.js (hunk 1 above)
Comment (Pyxxil) [reply src/App.js:76]: And makes it possible for the game screen and the journal to overlap.
