### PR TITLE
Bug/floor

### LINKED ISSUE #344: Floor 4-5 doesn't load
**Bug Summary**

Game crashes when entering floor 4-5

**Test Case(s)**

---

**Expected behavior**

Successfully enter floor

**Observed Behaviour**

Game crashes

**Steps To Reproduce**

1. Reached floor 4-4 stairs to 4-5
2. Enter stairs

**Environment**
- Version:
- OS: 
- Browser: 

---

**Code Examples**

**Stack Trace**

**Screenshots**

**Error Report**

---

**Additional context**

### PR DESCRIPTION
**Pull request by Frosty273**
GitHub Issue (If applicable): #344 

## PR Type

What kind of change does this PR introduce?

## What is the current behavior?
The game crashes when the player attempts to enter floor 4-5 by taking the stairs located on floor 4-4 up.

## What is the new behavior?

The floor 4-5 successfully loads when entering the stairs.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current upstream repo
- [] Added new tests to the test suite for the feature
- [ ] Tested the full test suite, and ensured that the feature does not break current build.
- [ ] Docs have been added/updated which fit (for bug fixes / features)
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal)
- [ ] Checked licensing of Frameworks/Libraries (if applicable) 

 
## Other information

Internal Issue (If applicable):

Fixes #344

### CODE REVIEW

**Comment by Matteas-Eden** [comment]
Do you mind linking the issue this resolves? And perhaps giving an overview of what causes the issue this PR resolves?

File: src/data/monsters/index.js [hunk 1]
```diff
@@ -34,6 +35,7 @@ const monsters = {
     ghost: Ghost,
     imp: Imp,
     lich: Lich,
+    'lich king': LicKing,
```
Comment (Pyxxil) [inline src/data/monsters/index.js]: How come this was changed to “LicKing”? Did you remove the ‘h’ that was here for a reason?

**Review by Pyxxil — CHANGES_REQUESTED** [review]

**Review by Pyxxil — APPROVED** [review]
Looks great!
